@startuml
start

:choose color;

:set starting position (fen) \n(default: standard starting position);

while (game over?) is (no)

:execute move;

while (valid move?) is (no)
  :ask for other move;
endwhile (yes)

:pick AI move \n(Based on Negamax);

:execute AI move;
endwhile(yes)

stop
@enduml